import { useState, useCallback } from 'react'
import type { Partner, PipelineStage, PartnerStatus } from '../types/partner'

const STAGE_DEFAULT_STATUS: Record<PipelineStage, PartnerStatus> = {
  inbound: 'submitted',
  doc_review: 'docs_pending',
  contracting: 'contract_sending',
  operating: 'preparing',
  terminated: 'contract_ended',
}

const MOCK_DATA: Partner[] = [
  {
    id: '1',
    contract_type: 'direct',
    pipeline_stage: 'inbound',
    status: 'submitted',
    apply_date: '2026-04-01',
    company_name: '가나다물류',
    applicant_name: '김철수',
    representative_name: null,
    email: 'chulsu@example.com',
    phone: '010-1234-5678',
    representative_phone: null,
    business_type: '법인',
    business_number: '123-45-67890',
    business_open_date: null,
    business_category: null,
    business_item: null,
    business_address: null,
    desired_region_text: '서울시 강남구',
    confirmed_zone_id: null,
    confirmed_zone_code: '표준서울강남A',
    pricing_plan: null,
    contract_template: null,
    experience_years: '1년 이상',
    rider_count: '10명~20명 미만',
    platform_experience: '바로고',
    dp_code: null,
    biz_id: null,
    sap_code: null,
    operating_start_date: null,
    assigned_team: '지원파트',
    assigned_user_name: '김현진',
    created_at: '2026-04-01T09:00:00',
    updated_at: '2026-04-01T09:00:00',
  },
  {
    id: '2',
    contract_type: 'direct',
    pipeline_stage: 'inbound',
    status: 'proposal_sent',
    apply_date: '2026-03-28',
    company_name: '빠른배달',
    applicant_name: '이영희',
    representative_name: null,
    email: 'fast@example.com',
    phone: '010-9876-5432',
    representative_phone: null,
    business_type: '일반과세',
    business_number: '987-65-43210',
    business_open_date: null,
    business_category: null,
    business_item: null,
    business_address: null,
    desired_region_text: '경기도 부천시',
    confirmed_zone_id: null,
    confirmed_zone_code: null,
    pricing_plan: null,
    contract_template: null,
    experience_years: '6개월 미만',
    rider_count: '5명~10명 미만',
    platform_experience: null,
    dp_code: null,
    biz_id: null,
    sap_code: null,
    operating_start_date: null,
    assigned_team: '지원파트',
    assigned_user_name: '윤은지',
    created_at: '2026-03-28T10:00:00',
    updated_at: '2026-03-29T14:00:00',
  },
  {
    id: '3',
    contract_type: 'direct',
    pipeline_stage: 'doc_review',
    status: 'docs_submitted',
    apply_date: '2026-03-20',
    company_name: '미래로직스',
    applicant_name: '이순신',
    representative_name: '이순신',
    email: 'future@example.com',
    phone: '010-5555-1234',
    representative_phone: '010-5555-1234',
    business_type: '법인',
    business_number: '555-12-34567',
    business_open_date: '2022-03-15',
    business_category: '운수업',
    business_item: '배달대행',
    business_address: '서울시 서초구 서초대로 100',
    desired_region_text: '서울시 서초구',
    confirmed_zone_id: null,
    confirmed_zone_code: '표준서울서초A',
    pricing_plan: '서울A',
    contract_template: '서울A',
    experience_years: '1년 이상',
    rider_count: '20명 이상',
    platform_experience: '바로고, 생각대로',
    dp_code: null,
    biz_id: null,
    sap_code: null,
    operating_start_date: null,
    assigned_team: '지원파트',
    assigned_user_name: '김현진',
    created_at: '2026-03-20T09:00:00',
    updated_at: '2026-03-25T11:00:00',
  },
  {
    id: '4',
    contract_type: 'direct',
    pipeline_stage: 'doc_review',
    status: 'docs_rejected',
    apply_date: '2026-03-18',
    company_name: '번개배달',
    applicant_name: '강감찬',
    representative_name: null,
    email: 'thunder@example.com',
    phone: '010-3333-4444',
    representative_phone: null,
    business_type: '일반과세',
    business_number: '333-44-55555',
    business_open_date: null,
    business_category: null,
    business_item: null,
    business_address: null,
    desired_region_text: '경기도 용인시',
    confirmed_zone_id: null,
    confirmed_zone_code: '표준경기용인기흥A',
    pricing_plan: null,
    contract_template: null,
    experience_years: null,
    rider_count: null,
    platform_experience: null,
    dp_code: null,
    biz_id: null,
    sap_code: null,
    operating_start_date: null,
    assigned_team: '지원파트',
    assigned_user_name: '윤은지',
    created_at: '2026-03-18T09:00:00',
    updated_at: '2026-03-22T16:00:00',
  },
  {
    id: '5',
    contract_type: 'direct',
    pipeline_stage: 'contracting',
    status: 'contract_sent',
    apply_date: '2026-03-10',
    company_name: '스마트딜',
    applicant_name: '유관순',
    representative_name: '유관순',
    email: 'smart@example.com',
    phone: '010-7777-8888',
    representative_phone: '010-7777-8888',
    business_type: '일반과세',
    business_number: '777-88-99999',
    business_open_date: '2024-05-01',
    business_category: '운수업',
    business_item: '소화물배송',
    business_address: '서울시 마포구 마포대로 200',
    desired_region_text: '서울시 마포구',
    confirmed_zone_id: null,
    confirmed_zone_code: '표준서울마포A',
    pricing_plan: '서울A',
    contract_template: '서울A',
    experience_years: '1년 이상',
    rider_count: '10명~20명 미만',
    platform_experience: null,
    dp_code: null,
    biz_id: null,
    sap_code: null,
    operating_start_date: null,
    assigned_team: '지원파트',
    assigned_user_name: '김현진',
    created_at: '2026-03-10T09:00:00',
    updated_at: '2026-04-02T10:00:00',
  },
  {
    id: '6',
    contract_type: 'direct',
    pipeline_stage: 'operating',
    status: 'active',
    apply_date: '2026-02-01',
    company_name: '스타플릿',
    applicant_name: '홍길동',
    representative_name: '홍길동',
    email: 'star@example.com',
    phone: '010-1111-2222',
    representative_phone: '010-1111-2222',
    business_type: '법인',
    business_number: '111-22-33333',
    business_open_date: '2023-01-10',
    business_category: '운수업',
    business_item: '배달대행',
    business_address: '서울시 은평구 은평로 50',
    desired_region_text: '서울시 은평구',
    confirmed_zone_id: null,
    confirmed_zone_code: '표준서울은평A',
    pricing_plan: '서울A',
    contract_template: '서울A',
    experience_years: '1년 이상',
    rider_count: '20명 이상',
    platform_experience: '바로고',
    dp_code: 'DP2602151234',
    biz_id: 'starfleet01',
    sap_code: '40012345',
    operating_start_date: '2026-02-15',
    assigned_team: '지원파트',
    assigned_user_name: '김현진',
    created_at: '2026-02-01T09:00:00',
    updated_at: '2026-02-15T09:00:00',
  },
]

export function useMockPartners() {
  const [partners, setPartners] = useState<Partner[]>(MOCK_DATA)

  const movePartner = useCallback(
    (partnerId: string, toStage: PipelineStage) => {
      setPartners((prev) =>
        prev.map((p) => {
          if (p.id !== partnerId) return p
          return {
            ...p,
            pipeline_stage: toStage,
            status: STAGE_DEFAULT_STATUS[toStage],
            updated_at: new Date().toISOString(),
          }
        })
      )
    },
    []
  )

  const addPartner = useCallback(() => {
    const newPartner: Partner = {
      id: Date.now().toString(),
      contract_type: 'direct',
      pipeline_stage: 'inbound',
      status: 'submitted',
      apply_date: new Date().toISOString().split('T')[0]!,
      company_name: '신규협력사 ' + Math.floor(Math.random() * 100),
      applicant_name: '테스트',
      representative_name: null,
      email: null,
      phone: null,
      representative_phone: null,
      business_type: null,
      business_number: null,
      business_open_date: null,
      business_category: null,
      business_item: null,
      business_address: null,
      desired_region_text: null,
      confirmed_zone_id: null,
      confirmed_zone_code: null,
      pricing_plan: null,
      contract_template: null,
      experience_years: null,
      rider_count: null,
      platform_experience: null,
      dp_code: null,
      biz_id: null,
      sap_code: null,
      operating_start_date: null,
      assigned_team: null,
      assigned_user_name: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
    setPartners((prev) => [newPartner, ...prev])
  }, [])

  return { partners, movePartner, addPartner }
}
